version: '3'
services:
  mediawiki:
    container_name: p05_mediawiki_anaponce
    image: mediawiki
    restart: always
    ports:
      - 8081:80
    links:
      - database
    volumes:
      - images:/var/www/html/images
      #- ./LocalSettings.php:/var/www/html/LocalSettings.php
  database:
    container_name: p05_mariadb_medwiki_anaponce
    image: mariadb
    restart: always
    environment:
    # He eliminado las variables de entorno que estaban por defecto en dockerHub, y me funciona solo con poner la
    # siguiente variable, tal y como lo hicimos la anterior vez que instalamos MediaWiki en clase
      MYSQL_ROOT_PASSWORD: 'anapcontra'
    volumes:
      - db:/var/lib/mysql
volumes:
  images:
  db:

  # Al finalizar la instalación, descargar el LocalSettings.php, ubicarlo en la misma carpeta de este docker-compose.yml 
  # y DESCOMENTAR LA LÍNEA 13 de este mismo archivo .yml (solo quitando el # )
  # Luego, ejecutar este comando -> docker-compose -f docker-compose.yml up
  # Finalmente, abrir mediawiki en el navegador -> localhost:8081