version: 'latest'
services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: anapcontra
# Usuario:root
# Contraseña:anapcontra