version: 'latest'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: p05_anaponce
      WORDPRESS_DB_PASSWORD: anapcontra
      WORDPRESS_DB_NAME: p05_anaponce_db
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: p05_anaponce_db
      MYSQL_USER: p05_anaponce
      MYSQL_PASSWORD: anapcontra
      MYSQL_ROOT_PASSWORD: anapadmin
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: